sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: jdbtFSWA1J/eUO57iEx5TdkxUxYxKjJHHlDls3z3R8TFxq/IlJzupB/un9fpjUAlMWiACHctMIwafIGId+dIgevRf/Lb7snHRQmdKU/vTSvJHj4An9j+mDgpv6mjs56TJ2xW93sH1ipEh5Ktu8oer/8aAF+AF5ZaU4G3BHgAo7eJcDgGBklT9k6R9zsEJgvQtT0ji0d+jbbT2asI+4tBBvIXNNjzdFdVCYnB/154oe7vVJuh8T7zgJb1Nr3k1k/qIub2Z0kLTMTb6uj/hL8eXlv93ztNg6qaycCRvH2KKg8MKM03lfjfLIcr8wjWVMdd7r7Gm8cTzLx4vOeGz9UkPtwb35ERvSHfhkBtMPc0P/Paob3GZB6gDCSOqE0sRI5JX8ongOTq6pxlt5GnFMNWzwCeaEARiejt/ghzBIrreSGOSYiVtCjLPh1KjqqUYHrG0BQETw980v1zy9/P9Xv60d8P3wPVPHESpGOx2nTMRms2XP5yLeEN3gF99UxlfePNypCRxJFksILgdOQT4vsUuDWBfKGUfEwg+ICkb4T5XGxErmiAHn1GcsMaUbwIZVwD0GAg0NbPcfZNHnaDeJlsWSHp1nWFDjxnqyGWuIwNrsernHbnQCOOdkD+/p2lvcS06GoE0GuEaq5phuoWtOIrgYZC625vz9z5QtSS+i+4q58=
before_install:
- openssl aes-256-cbc -K $encrypted_d8bd89c86aac_key -iv $encrypted_d8bd89c86aac_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  5
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
